---
type_regex: !!map
  deposit: "^DEPOSIT|^INVITED_REFERRAL_REWARD"
  withdraw: "^WITHDRAW"
  interest: "^REPAYMENT"

csv_fieldnames:
  booking_date: 'Date'
  booking_date_format: '%Y-%m-%d'
  booking_id: 'Transaction ID'
  booking_type: 'Transaction Type'
  booking_value: 'Turnover'
  booking_details: 'Asset ID'
